import resImg from "./img/face.jpg";

function generateHomePage() {
    const content = document.querySelector("#content");
    content.innerHTML = "";
    const resName = document.createElement("div");
    const summary = document.createElement("div");
    const hours = document.createElement("div");
    const location = document.createElement("div");
    const hoursTitle = document.createElement("h2");
    const locationTitle = document.createElement("h2");
    const monday = document.createElement("p");
    const tuesday = document.createElement("p");
    const wednesday = document.createElement("p");
    const thursday = document.createElement("p");
    const friday = document.createElement("p");
    const saturday = document.createElement("p");
    const sunday = document.createElement("p");
    const locationText = document.createElement("p");
    const locationText2 = document.createElement("p");
    const locationText3 = document.createElement("p");
    const img = new Image();
    img.src = resImg;
    resName.classList.add("res-name");
    summary.classList.add("summary");
    hours.classList.add("hours");
    location.classList.add("location");
    img.src = resImg;
    resName.textContent = "Damsels Bites";
    summary.textContent = "A restaurant that serves the best food in the world. We have a wide variety of dishes to choose from, and we are sure you will find something you love.";
    hoursTitle.textContent = "Hours";
    monday.textContent = "Monday: 10am - 11pm";
    tuesday.textContent = "Tuesday: 10am - 11pm";
    wednesday.textContent = "Wednesday: 10am - 11pm";
    thursday.textContent = "Thursday: 10am - 11pm";
    friday.textContent = "Friday: 10am - 11pm";
    saturday.textContent = "Saturday: 10am - 11pm";
    sunday.textContent = "Sunday: 10am - 11pm";
    locationTitle.textContent = "Location";
    locationText.textContent = "Fort Frogs.";
    locationText2.textContent = "Kingdom Frogs";
    locationText3.textContent = "Frog Palace";
    content.appendChild(resName);
    content.appendChild(img);
    content.appendChild(summary);
    content.appendChild(hours);
    content.appendChild(location);
    hours.appendChild(hoursTitle);
    hours.appendChild(monday);
    hours.appendChild(tuesday);
    hours.appendChild(wednesday);
    hours.appendChild(thursday);
    hours.appendChild(friday);
    hours.appendChild(saturday);
    hours.appendChild(sunday);
    location.appendChild(locationTitle);
    location.appendChild(locationText);
    location.appendChild(locationText2);
    location.appendChild(locationText3);
}
export default generateHomePage;